% MAKE_METRICS calculates ICI and CCI metrics for a range of emissions
% scenarios generated by the MAKE_SCENARIOS script.

% Load scenarios infrmation and extract important variables.
addpath('./tools')
load scenarios; %vectors of t1 (years), emissions (GtC), concentrations
                %(ppm), and radaitive forcing (W/m^2)                
                
%% Calculate peaking year for each sceanrio.
[~,peak_year] = max(fmat_OLD);
peak_year     = peak_year + 2009;

%% Calculate metrics.
metric_inputs; %output: ICI_values and CCI_values

% Calculate ICI metrics:
ICI_CH4A=ICI_calculator(ICI_valuesCH4,peak_year(1) - 2009);
ICI_CH4B=ICI_calculator(ICI_valuesCH4,peak_year(2) - 2009);
ICI_CH4C=ICI_calculator(ICI_valuesCH4,peak_year(3) - 2009);
ICI_CH4D=ICI_calculator(ICI_valuesCH4,peak_year(4) - 2009);
ICI_CH4E=ICI_calculator(ICI_valuesCH4,peak_year(5) - 2009);

ICI_N2OA=ICI_calculator(ICI_valuesN2O,peak_year(1) - 2009);
ICI_N2OB=ICI_calculator(ICI_valuesN2O,peak_year(2) - 2009);
ICI_N2OC=ICI_calculator(ICI_valuesN2O,peak_year(3) - 2009);
ICI_N2OD=ICI_calculator(ICI_valuesN2O,peak_year(4) - 2009);
ICI_N2OE=ICI_calculator(ICI_valuesN2O,peak_year(5) - 2009);

% Calculate CCI metrics:
CCI_CH4A=CCI_calculator(CCI_valuesCH4,peak_year(1) - 2009);
CCI_CH4B=CCI_calculator(CCI_valuesCH4,peak_year(2) - 2009);
CCI_CH4C=CCI_calculator(CCI_valuesCH4,peak_year(3) - 2009);
CCI_CH4D=CCI_calculator(CCI_valuesCH4,peak_year(4) - 2009);
CCI_CH4E=CCI_calculator(CCI_valuesCH4,peak_year(5) - 2009);

CCI_N2OA=CCI_calculator(CCI_valuesN2O,peak_year(1) - 2009);
CCI_N2OB=CCI_calculator(CCI_valuesN2O,peak_year(2) - 2009);
CCI_N2OC=CCI_calculator(CCI_valuesN2O,peak_year(3) - 2009);
CCI_N2OD=CCI_calculator(CCI_valuesN2O,peak_year(4) - 2009);
CCI_N2OE=CCI_calculator(CCI_valuesN2O,peak_year(5) - 2009);

% Add GWP100 and GWP20 values for reference.
GWP_CH4 = ones(n,1)*25 ;
GWP_N2O = ones(n,1)*298;

% Calculate metric vectors.
ICI_mat  = [ICI_CH4A ICI_CH4B ICI_CH4C ICI_CH4D ICI_CH4E];
CCI_mat  = [CCI_CH4A CCI_CH4B CCI_CH4C CCI_CH4D CCI_CH4E];
GWP_mat  = [GWP_CH4  GWP_CH4  GWP_CH4  GWP_CH4  GWP_CH4 ];
ICI_matN = [ICI_N2OA ICI_N2OB ICI_N2OC ICI_N2OD ICI_N2OE];
CCI_matN = [CCI_N2OA CCI_N2OB CCI_N2OC CCI_N2OD CCI_N2OE];
GWP_matN = [GWP_N2O  GWP_N2O  GWP_N2O  GWP_N2O  GWP_N2O ];

%% Clear variables.
clear('ICI_valuesCH4','CCI_valuesCH4','GWP_CH4','GWP_N2O','ICI_CH4A',...
    'ICI_CH4B','ICI_CH4C','ICI_CH4D','ICI_CH4E','ICI_N2OA','ICI_N2OB',...
    'ICI_N2OC','ICI_N2OD','ICI_N2OE','CCI_CH4A','CCI_CH4B','CCI_CH4C',...
    'CCI_CH4D','CCI_CH4E','CCI_N2OA','CCI_N2OB','CCI_N2OC','CCI_N2OD',...
    'CCI_N2OE','ICI_valuesN2O','CCI_valuesN2O')
